### ISSUE TITLE
Google Login doesn't work on demo

### ISSUE THREAD

**Issue by mrzmyr** [ndom91/katalog#1]
![Screen Shot 2020-10-10 at 19 01 17](https://user-images.githubusercontent.com/746429/95660872-088eaf00-0b2b-11eb-95f9-36ae2fef4bac.png)

**URL**: https://katalog.newtelco.dev/auth/signin

**Comment by ndom91** [comment]
Yeah sorry it's only setup to work with Google accounts from my company's domain. 

You can use the email, "magic link" type login for now if you wanna take a look around.

**Comment by ndom91** [comment]
This is definitely still a WIP though. If you're looking for something similar I'm happy to collaborate!
